version: "3.7"
volumes:
  node_modules_frontend: {}
  strapi_uploads:
    external: true
services:

  common-frontend:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  strapi:
    restart: always
    environment:
      - HOST=strapi
      - PORT=1337
      - URL_ADMIN=http://web.fsmpi:8000/admin
      - URL_SERVER=https://fsmpi.uni-bayreuth.de/v1
    # SWITCH TO ./strapi-backend-v5 AFTER STABILIZING v4 BASELINE
    build: ./strapi-backend
    image: strapi:1.0.0
    volumes:
      - strapi_uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.40
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vuecms:
    restart: always
    build: ./frontend
    image: vuecms:1.0.0
    working_dir: "/var/vuecms"
    volumes:
      - ./frontend:/var/vuecms
      - /var/vuecms/dist-ssr
      - /var/vuecms/production
      - node_modules_frontend:/var/vuecms/node_modules
    ports:
      - "5000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.50
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  homepage-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.2.0/24
